http:
  port: 8000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  borger:
    host: localhost
    paths: '/borger/*'
  bank:
    host: localhost
    paths: '/bank/*'
  skat:
    host: localhost
    paths: '/skat/*'
serviceEndpoints:
  borgerService:
    url: 'http://localhost:8001'
  bankService:
    url: 'http://localhost:8002'
  skatService:
    url: 'http://localhost:8003'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - rewrite
pipelines:
  borgerPipeline:
    apiEndpoints:
      - borger
    policies:
      - log:
          - action:
              message: ${req.method} ${req.originalUrl} ${res.statusCode}
      - rewrite:
          condition:
            name: pathmatch
            match: '/borger/:route*'
          action:
            rewrite: '/:route'
      - proxy:
          action:
            serviceEndpoint: borgerService
            changeOrigin: true
  bankPipeline:
    apiEndpoints:
      - bank
    policies:
      - log:
          - action:
              message: ${req.method} ${req.originalUrl} ${res.statusCode}
      - rewrite:
          condition:
            name: pathmatch
            match: '/bank/:route*'
          action:
            rewrite: '/:route'
      - proxy:
          action:
            serviceEndpoint: bankService
            changeOrigin: true
  skatPipeline:
    apiEndpoints:
      - skat
    policies:
      - log:
          - action:
              message: ${req.method} ${req.originalUrl} ${res.statusCode}
      - rewrite:
          condition:
            name: pathmatch
            match: '/skat/:route*'
          action:
            rewrite: '/:route'
      - proxy:
          action:
            serviceEndpoint: skatService
            changeOrigin: true